### ISSUE TITLE
Won't work in node v0.12

### ISSUE THREAD

**Issue by jasonslyvia** [roshanca/autochangelog#2]
It throws following error whereas node v5.1 works fine.

```
/Users/xxx/.nvm/versions/node/v0.12.7/lib/node_modules/autochangelog/index.js:70
            const milestonesApi = `${api}/projects/${encodeURIComponent(projec
                                  ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by roshanca** [comment]
It seems that the template string is not supported by the node of this version, even with the harmony flag.

I'm sure that 4.0+ node contains the feature. But if lower than that, what i can advise so far is installing 3.x version instead:

```
npm install -g autochangelog@3.x
```
