### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by MatLeRock** [roshanca/autochangelog#7]
Win 7 (64) - Node 5.6.0 - NPM 3.6.0

```
C:\Users\mock\git\npp>autochangelog 
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at Object.<anonymous> (C:\Users\mock\AppData\Roaming\npm\node_modules\autochangelog\index.js:54:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

**Comment by roshanca** [comment]
Sorry, can u offer the result of `process.env.HOME` in REPL of node.

**Comment by maxfriedmann** [comment]
I think @MatLeRock is using windows, just like me. Please accept my PR.

**Comment by roshanca** [comment]
@maxfriedmann thx~
